document.write("<!DOCTYPE html>");
document.write("<html>");
document.write("    <head>");
document.write("        <title>footer<\/title>");
document.write("        <style>");
document.write("            footer{");
document.write("                background-color: aliceblue;");
document.write("                height: 300px;");
document.write("            }");
document.write("            #footerpic{");
document.write("                margin-left: 644px;");
document.write("            }");
document.write("            ");
document.write("            #footer{");
document.write("                font-size: 30px;");
document.write("                font-family: Copperplate, Papyrus, fantasy;");
document.write("                text-align: justify;");
document.write("                text-align: center;");
document.write("            }");
document.write("            a:link{text-decoration: none;}");
document.write("            a:hover {");
document.write("             color: #000000; ");
document.write("            text-decoration: underline;");
document.write("                }");
document.write("                #right{");
document.write("                    font-size: 30px;");
document.write("                font-family: Copperplate, Papyrus, fantasy;");
document.write("                margin-right: 300px;");
document.write("                }");
document.write("        <\/style>");
document.write("    <\/head>");
document.write("");
document.write("    <body>");
document.write("        <footer>");
document.write("            <hr>");
document.write("            <img id=\"footerpic\" src = \"saf-logo.png\" alt = \"Yuc students activities logo\" width=\"150\" height=\"100\"> ");
document.write("            <div id=\"footer\">");
document.write("                <a href=\"About Us.html\">About Us<\/a> ");
document.write("                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
document.write("                <a href=\"Contact Us.jsp\">Contact Us<\/a>");
document.write("                <br>");
document.write("                <br> ");
document.write("                <a href=\"/CS 378-project/src/main/java/cs378package/Logout.java\"> Log Out <\/a> ");
document.write("                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;");
document.write("                <a href=\"Annoucement.html\">Announcement<\/a>");
document.write("            <\/div>");
document.write("            ");
document.write("             <\/footer>");
document.write("        ");
document.write("    <\/body>");
document.write("<\/html>");